#!/bin/sh

RELEASE_HOME='release'
BIN_DIR='bin'
COMMON_DIR='common'
EMAIL_DIR='email_lib'
MAKE_DIR='make_include'
POP3_DIR='pop3'
IMAP_DIR='imap'
SERVICE_DIR='service_plugins'
LOGS_INFO='logs'
CONFIGS_DIR='config'
DATA_DIR='data'
LIB_DIR='lib'
TOKEN_DIR='token'
SDK_DIR='sdk'
BACKUP_DIR='backup'
COMMON_LIB='common.so'
SCHEDULER_LIB='epoll_scheduler.so'
EMAIL_LIB='email_lib.so'
POP3_NAME='pop3'
IMAP_NAME='imap'

rm -rf $RELEASE_HOME
mkdir $RELEASE_HOME
mkdir $RELEASE_HOME/$BIN_DIR
mkdir $RELEASE_HOME/$SERVICE_DIR
mkdir $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR
mkdir $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR
mkdir $RELEASE_HOME/$LOGS_INFO
mkdir $RELEASE_HOME/$LOGS_INFO/$POP3_DIR
mkdir $RELEASE_HOME/$LOGS_INFO/$IMAP_DIR
mkdir $RELEASE_HOME/$CONFIGS_DIR
mkdir $RELEASE_HOME/$CONFIGS_DIR/$POP3_DIR
mkdir $RELEASE_HOME/$CONFIGS_DIR/$IMAP_DIR
mkdir $RELEASE_HOME/$DATA_DIR
mkdir $RELEASE_HOME/$LIB_DIR
mkdir $RELEASE_HOME/$TOKEN_DIR
mkdir $RELEASE_HOME/$DATA_DIR/$POP3_DIR
mkdir $RELEASE_HOME/$DATA_DIR/$IMAP_DIR
mkdir $RELEASE_HOME/$SDK_DIR
mkdir $RELEASE_HOME/$SDK_DIR/$COMMON_DIR
mkdir $RELEASE_HOME/$SDK_DIR/$COMMON_DIR/include
mkdir $RELEASE_HOME/$SDK_DIR/$EMAIL_DIR
mkdir $RELEASE_HOME/$SDK_DIR/$EMAIL_DIR/include
mkdir $RELEASE_HOME/$SDK_DIR/$MAKE_DIR
mkdir $RELEASE_HOME/$SDK_DIR/$SERVICE_DIR
mkdir $RELEASE_HOME/$SDK_DIR/$SERVICE_DIR/include
mkdir $RELEASE_HOME/$SDK_DIR/$SERVICE_DIR/sample
cp scripts/install* $RELEASE_HOME
cp apollo/apollo.bin $RELEASE_HOME/$BIN_DIR
cp scripts/apollo.sh $RELEASE_HOME/$BIN_DIR
cp scripts/apollo.service $RELEASE_HOME/$BIN_DIR
cp pop3/$POP3_NAME $RELEASE_HOME/$BIN_DIR
cp pop3/$DATA_DIR/*.txt $RELEASE_HOME/$DATA_DIR/$POP3_DIR
cp pop3/$CONFIGS_DIR/pop3.cfg $RELEASE_HOME/$CONFIGS_DIR/pop3.cfg
cp imap/$IMAP_NAME $RELEASE_HOME/$BIN_DIR
cp imap/$DATA_DIR/*.txt $RELEASE_HOME/$DATA_DIR/$IMAP_DIR
cp imap/$CONFIGS_DIR/imap.cfg $RELEASE_HOME/$CONFIGS_DIR/imap.cfg
cp common/$COMMON_LIB $RELEASE_HOME/$LIB_DIR
cp epoll_scheduler/$SCHEDULER_LIB $RELEASE_HOME/$LIB_DIR
cp email_lib/$EMAIL_LIB $RELEASE_HOME/$LIB_DIR
cp $SERVICE_DIR/ip_container/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/ip_container.svc
cp $SERVICE_DIR/ip_filter/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/ip_filter.svc
cp $SERVICE_DIR/event_proxy/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/event_proxy.svc
cp $SERVICE_DIR/str_filter/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/user_filter.svc
cp $SERVICE_DIR/log_plugin/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/log_plugin.svc
cp $SERVICE_DIR/midb_agent/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/midb_agent.svc
cp $SERVICE_DIR/mysql_adaptor/*.svc $RELEASE_HOME/$SERVICE_DIR/$POP3_DIR/mysql_adaptor.svc
cp $SERVICE_DIR/$CONFIGS_DIR/$POP3_DIR/*.cfg $RELEASE_HOME/$CONFIGS_DIR/$POP3_DIR
cp $SERVICE_DIR/$DATA_DIR/$POP3_DIR/*.txt $RELEASE_HOME/$DATA_DIR/$POP3_DIR
cp $SERVICE_DIR/ip_container/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/ip_container.svc
cp $SERVICE_DIR/ip_filter/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/ip_filter.svc
cp $SERVICE_DIR/event_proxy/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/event_proxy.svc
cp $SERVICE_DIR/event_stub/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/event_stub.svc
cp $SERVICE_DIR/str_filter/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/user_filter.svc
cp $SERVICE_DIR/log_plugin/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/log_plugin.svc
cp $SERVICE_DIR/midb_agent/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/midb_agent.svc
cp $SERVICE_DIR/mysql_adaptor/*.svc $RELEASE_HOME/$SERVICE_DIR/$IMAP_DIR/mysql_adaptor.svc
cp $SERVICE_DIR/$CONFIGS_DIR/$IMAP_DIR/*.cfg $RELEASE_HOME/$CONFIGS_DIR/$IMAP_DIR
cp $SERVICE_DIR/$DATA_DIR/$IMAP_DIR/*.txt $RELEASE_HOME/$DATA_DIR/$IMAP_DIR
dos2unix $RELEASE_HOME/$BIN_DIR/*.sh
chmod a+x $RELEASE_HOME/$BIN_DIR/*.sh
cp common/include/*.h $RELEASE_HOME/$SDK_DIR/$COMMON_DIR/include
cp email_lib/include/*.h $RELEASE_HOME/$SDK_DIR/$EMAIL_DIR/include
cp make_include/* $RELEASE_HOME/$SDK_DIR/$MAKE_DIR
cp service_plugins/include/*.h $RELEASE_HOME/$SDK_DIR/$SERVICE_DIR/include
cp service_plugins/sample/* $RELEASE_HOME/$SDK_DIR/$SERVICE_DIR/sample
cd $RELEASE_HOME/$SERVICE_DIR && ln -s ../$LIB_DIR .
cd ../$SDK_DIR && ln -s ../$LIB_DIR .
