#!/bin/sh


mkdir /var/posidon
cp -R * /var/posidon
ln -s /var/herculiz /var/posidon/gateway
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /var/herculiz -s /bin/nologin
touch /var/posidon/logs/posidon_log.txt
chown -R herculiz:herculiz /var/posidon
chmod -R a+wr /var/posidon
mv /var/posidon/bin/posidon.bin /usr/bin/posidon
mv /var/posidon/bin/posidon.sh /etc/rc.d/init.d/posidon
rm -f /var/posidon/bin/posidon.service
chkconfig --add posidon
chown -R herculiz:herculiz /var/posidon
echo "POSIDON domain administration web agent is installed OK"
echo
