#ifndef _H_STRING_TABLE_
#define _H_STRING_TABLE_

enum {
	RES_HOST_ID,
	RES_DEFAULT_DOMAIN,
	RES_RUNNING_IDENTITY,
	RES_DOMAIN_LIST_VALID,
	
	RES_DEQUEUE_PATH,
	RES_DEQUEUE_TAPE_SIZE,
	RES_DEQUEUE_MAXIMUM_MEM,

	RES_MPC_PLUGIN_PATH,
	RES_WORK_THREADS_MIN,
	RES_WORK_THREADS_MAX,
	RES_FREE_CONTEXT_NUM,
	RES_CONTEXT_AVERAGE_MIME,

	RES_CONSOLE_SERVER_IP,
	RES_CONSOLE_SERVER_PORT,
	
	RES_ADMIN_MAILBOX,
	RES_SERVICE_PLUGIN_PATH,
    RES_CONFIG_FILE_PATH,
    RES_DATA_FILE_PATH,
    MAX_RES_CONFG_VAR_NUM
};


static struct {
#define MAX_VAR_LEN     256
    int  var_id;
    char name[MAX_VAR_LEN];
} g_string_table[MAX_RES_CONFG_VAR_NUM] = {
	{ RES_HOST_ID, "HOST_ID"},
	{ RES_DEFAULT_DOMAIN, "DEFAULT_DOMAIN" },
	{ RES_RUNNING_IDENTITY, "RUNNING_IDENTITY" },
	{ RES_DOMAIN_LIST_VALID, "DOMAIN_LIST_VALID" },
	
	{ RES_DEQUEUE_PATH, "DEQUEUE_PATH" },
	{ RES_DEQUEUE_TAPE_SIZE, "DEQUEUE_TAPE_SIZE" },
	{ RES_DEQUEUE_MAXIMUM_MEM, "DEQUEUE_MAXIMUM_MEM" },
	
	{ RES_MPC_PLUGIN_PATH, "MPC_PLUGIN_PATH" },
	{ RES_WORK_THREADS_MIN, "WORK_THREADS_MIN" },
	{ RES_WORK_THREADS_MAX, "WORK_THREADS_MAX" },
	{ RES_FREE_CONTEXT_NUM, "FREE_CONTEXT_NUM" },
	{ RES_CONTEXT_AVERAGE_MIME, "CONTEXT_AVERAGE_MIME" },
	
	{ RES_CONSOLE_SERVER_IP, "CONSOLE_SERVER_IP" },
	{ RES_CONSOLE_SERVER_PORT, "CONSOLE_SERVER_PORT" },
	
	{ RES_ADMIN_MAILBOX, "ADMIN_MAILBOX"},
	{ RES_SERVICE_PLUGIN_PATH, "SERVICE_PLUGIN_PATH" },
	{ RES_CONFIG_FILE_PATH, "CONFIG_FILE_PATH" },
    { RES_DATA_FILE_PATH, "DATA_FILE_PATH" }
};

#endif /* _H_STRING_TABLE_ */
