#!/bin/sh

chmod a+x LIBRARY/scripts/*
chmod a+x MTA_SYSTEM/scripts/*
chmod a+x MRA_SYSTEM/scripts/*
chmod a+x EXCHANGE_SYSTEM/scripts/*
chmod a+x AGENT_SERVICE/scripts/*
chmod a+x DOMAIN_ADMIN/scripts/*
chmod a+x SYSTEM_ADMIN/scripts/*
chmod a+x ARCHIVE_SYSTEM/scripts/*
cd LIBRARY && make && cd ..
cd MTA_SYSTEM && make && make release && cd ..
cd MRA_SYSTEM && make && make release && cd ..
cd EXCHANGE_SYSTEM && make && make release && cd ..
cd AGENT_SERVICE && make && make release && cd ..
cd DOMAIN_ADMIN && make && make release && cd ..
cd SYSTEM_ADMIN && make && make release && cd ..
cd ARCHIVE_SYSTEM && make && make release && cd ..
