#!/bin/sh

_target=""
_symlinks=1
HEMXX="$PWD"
fdupes -q -p -n -H -o name -r * | while read _file; do
	if test -z "$_target"; then
		_target="${_file#$HEMXX}"
		continue
	fi
	if test -z "$_file"; then
		_target=""
		continue
	fi
	tf=$(echo -en "$_file" | perl -pe 's{[^/]+/}{../}g;s{/[^/]+$}{}')
	echo ln -sf "$tf/$_target" "$_file"
	ln -sf "$tf/$_target" "$_file"
done
