#!/bin/bash

if [ -z "$1" ]; then
	exit 0
fi
libtool="$1"; shift
input="$1"; shift
output="$1"; shift

case "$input" in #((
	*.la)
		. "$input"
		if test -z "$dlname"; then
			exit 0
		fi
		real=$(dirname "$input")"/.libs/$dlname"
		# ldd loads all dependencies, which nm would not do.
		if ldd -r "$real" 2>/dev/null | c++filt | grep "undefined symbol"; then
			rm "$output"
			exit 1
		fi
		;;
	*)
		if "${libtool}" --mode=execute ldd -r "$input" 2>/dev/null | c++filt | \
		   grep "undefined symbol"; then
			rm "$output"
			exit 1
		fi
		;;
esac
if test -n "$output"; then
	>"$output"
fi
exit 0
