#!/bin/sh
DST_DIR="$1"
PARA_SIZE="$#"

if [ $PARA_SIZE -lt 2 ];then
	echo "Required more than 2 parameters!"
	exit 1
fi
if [ -d $DST_DIR ];then
	rm -rf $DST_DIR
fi

mkdir -p $DST_DIR

for symbol_link in $*
do
	if [ "X$symbol_link" != "X$DST_DIR" ];then
		#echo "symbol_link:$symbol_link"
		#echo "first parameter:$DST_DIR"
		cd $DST_DIR
			ln -s $symbol_link .
		cd ..
	fi
done
