#!/bin/sh


mkdir /var/athena
cp -R * /var/athena
touch /var/athena/logs/athena_log.txt
chown -R apache /var/athena
chmod -R a+wr /var/athena
mv /var/athena/bin/athena.bin /usr/bin/athena
mv /var/athena/bin/athena.sh /etc/rc.d/init.d/athena
rm -f /var/athena/bin/athena.service
chkconfig --add athena
chown -R apache. /var/athena
echo "ATHENA inbound administration is installed OK"
echo
