#!/bin/sh


mkdir /var/herculiz
cp -R * /var/herculiz
/var/herculiz/bin/create_queue.sh /var/herculiz/queue
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /var/herculiz -s /bin/nologin
chown -R herculiz:herculiz /var/herculiz
chmod -R a+rw /var/herculiz
mv /var/herculiz/bin/herculiz.bin /usr/bin/herculiz
mv /var/herculiz/bin/herculiz.sh /etc/rc.d/init.d/herculiz
rm -f /var/herculiz/bin/herculiz.service
chkconfig --add herculiz
echo "HERCULIZ MTA is installed OK"
echo
