#pragma once
enum {
	MIDB_E_UNKNOWN_COMMAND = 0,
	MIDB_E_PARAMETER_ERROR = 1,
	MIDB_E_HASHTABLE_FULL = 2,
	MIDB_E_NO_FOLDER = 3,
	MIDB_E_NO_MEMORY = 4,
	MIDB_E_NO_MESSAGE = 5,
	MIDB_E_DIGEST = 6,
	MIDB_E_FOLDER_EXISTS = 7,
	MIDB_E_FOLDER_LIMIT = 8,
	MIDB_E_MAILBOX_FULL = 9,
	MIDB_E_NO_DELETE = 10,
	MIDB_E_STORE_NOT_LOADED = 11,
	MIDB_E_STORE_BUSY = 12,
	MIDB_E_NETIO = 13,
};
