/*
 * Includers need to define EDEF(name,id), EUNDEF(id), EOBSOL(name,id)
 *
 * If a ZRPC is added, more work is needed:
 * - include/gromox/zcore_rpc.hpp: struct declaration
 * - exch/zcore/names.cpp: last_id
 * - exch/zcore/rpc_ext.cpp, php_mapi/rpc_ext.cpp: (de)serialize functions
 */
EDEF(logon, 0x00)
EDEF(unloadobject, 0x01)
EDEF(openentry, 0x02)
EDEF(openstoreentry, 0x03)
EDEF(openabentry, 0x04)
EDEF(resolvename, 0x05)
EUNDEF(0x06)
EDEF(getpermissions, 0x07)
EDEF(modifypermissions, 0x08)
EDEF(modifyrules, 0x09)
EDEF(getabgal, 0x0a)
EDEF(loadstoretable, 0x0b)
EDEF(openstore, 0x0c)
EDEF(openprofilesec, 0x0d)
EDEF(loadhierarchytable, 0x0e)
EDEF(loadcontenttable, 0x0f)
EDEF(loadrecipienttable, 0x10)
EUNDEF(0x11)
EDEF(loadruletable, 0x12)
EDEF(createmessage, 0x13)
EDEF(deletemessages, 0x14)
EDEF(copymessages, 0x15)
EDEF(setreadflags, 0x16)
EDEF(createfolder, 0x17)
EDEF(deletefolder, 0x18)
EDEF(emptyfolder, 0x19)
EDEF(copyfolder, 0x1a)
EDEF(getstoreentryid, 0x1b)
EDEF(entryidfromsourcekey, 0x1c)
EDEF(storeadvise, 0x1d)
EDEF(unadvise, 0x1e)
EDEF(notifdequeue, 0x1f)
EDEF(queryrows, 0x20)
EDEF(setcolumns, 0x21)
EDEF(seekrow, 0x22)
EDEF(sorttable, 0x23)
EDEF(getrowcount, 0x24)
EDEF(restricttable, 0x25)
EDEF(findrow, 0x26)
EDEF(createbookmark, 0x27)
EDEF(freebookmark, 0x28)
EDEF(getreceivefolder, 0x29)
EDEF(modifyrecipients, 0x2a)
EDEF(submitmessage, 0x2b)
EDEF(loadattachmenttable, 0x2c)
EDEF(openattachment, 0x2d)
EDEF(createattachment, 0x2e)
EDEF(deleteattachment, 0x2f)
EDEF(setpropvals, 0x30)
EDEF(getpropvals, 0x31)
EDEF(deletepropvals, 0x32)
EDEF(setmessagereadflag, 0x33)
EDEF(openembedded, 0x34)
EDEF(getnamedpropids, 0x35)
EDEF(getpropnames, 0x36)
EDEF(copyto, 0x37)
EDEF(savechanges, 0x38)
EDEF(hierarchysync, 0x39)
EDEF(contentsync, 0x3a)
EDEF(configsync, 0x3b)
EDEF(statesync, 0x3c)
EDEF(syncmessagechange, 0x3d)
EDEF(syncfolderchange, 0x3e)
EDEF(syncreadstatechanges, 0x3f)
EDEF(syncdeletions, 0x40)
EDEF(hierarchyimport, 0x41)
EDEF(contentimport, 0x42)
EDEF(configimport, 0x43)
EDEF(stateimport, 0x44)
EDEF(importmessage, 0x45)
EDEF(importfolder, 0x46)
EDEF(importdeletion, 0x47)
EDEF(importreadstates, 0x48)
EDEF(getsearchcriteria, 0x49)
EDEF(setsearchcriteria, 0x4a)
EDEF(messagetorfc822, 0x4b)
EOBSOL(rfc822tomessage_v1, 0x4c)
EDEF(messagetoical, 0x4d)
EDEF(icaltomessage, 0x4e)
EDEF(messagetovcf, 0x4f)
EDEF(vcftomessage, 0x50)
EDEF(uinfo, 0x51)
EDEF(checksession, 0x52)
EOBSOL(getuseravailability, 0x53)
EDEF(setpasswd, 0x54)
EDEF(linkmessage, 0x55)
EDEF(rfc822tomessage, 0x56)
EOBSOL(icaltomessage2, 0x57)
EDEF(imtomessage2, 0x58)
EDEF(essdn_to_username, 0x59)
EDEF(logon_token, 0x5a)
EDEF(getuserfreebusy, 0x5b)
EDEF(getuserfreebusyical, 0x5c)
EDEF(logon_np, 0x5d)
