.TH gromox 7 "" "Gromox" "Gromox admin reference"
.SH Overview
.PP
Gromox is a groupware server capable of serving as a replacement for Microsoft
Exchange. Connectivity options include Outlook Anywhere (RPC-over-HTTP),
IMAP/POP3, an SMTP-speaking LDA, and a PHP module with a Z-MAPI function
subset. Gromox is preferably used in conjunction with a proven httpd, MTA and
spam solution (e.g. nginx, Postfix, rspamd) to form a comprehensive mail
system.
.SH Synopsis
.PP
gromox \(em overview of the Gromox groupware server
.SH Configuration files
.PP
Program configuration files reside within /etc/gromox. Most of the programs
have a \fBconfig_file_path\fP directive with which the search path for further
config files can be specified. For example, http(8gx) defaults to
config_file_path=/etc/gromox/http:/etc/gromox, so the mysql_adaptor(4gx) plugin
as loaded by http will first try
/etc/gromox/http/mysql_adaptor.cfg, then /etc/gromox/mysql_adaptor.cfg. This
allows having one file that is shared between multiple programs as well as
being able to override on a per program-basis.
.SH Databases
.IP \(bu 4
User information is held in a MariaDB/MySQL database. This database can be
accessed by multiple Gromox servers, and so enables distributed Gromox
operation. The MariaDB system itself provides the necessary utilities for
distributing or replicating this database.
.IP \(bu 4
Per-user e-mail messages are stored in a SQLite database (e.g.
/var/lib/gromox/user/m1/1/1/exchange.sqlite3), as is a message index (e.g.
/var/lib/gromox/user/m1/1/1/midb.sqlite3). These are normally only used by one
system, but can be shared through network filesystems provided that file
locking is properly implemented in the filesystem driver. Normal file
mechanisms can be used to backup or transfer the database to another Gromox
host.
.SH Exchange subsystem
.IP \(bu 4
autodiscover(4gx) \(em Autodiscover HTTP Service Protocol handler
.IP \(bu 4
exchange_emsmdb(4gx) \(em http(8gx) processing plugin for the Wire Format
Protocol (Outlook/Exchange RPCs).
.IP \(bu 4
exchange_nsp(4gx) \(em http(8gx) processing plugin for the Exchange Server Name
Service Provider Interface Protocol.
.IP \(bu 4
exchange_rfr(4gx) \(em http(8gx) processing plugin for the Address Book Name
Service Provider Interface Referral Protocol.
.IP \(bu 4
exmdb_provider(4gx) \(em http(8gx) service plugin for exmdb connections
.IP \(bu 4
http(8gx)
.IP \(bu 4
midb(8gx)
.IP \(bu 4
mod_cache(4gx) \(em http(8gx) processing plugin for serving objects from a
local filesystem
.IP \(bu 4
mod_fastcgi(4gx) \(em http(8gx) processing plugin for proxying requests to
FastCGI servers
.IP \(bu 4
mod_proxy(4gx) \(em http(8gx) processing plugin for proxying requests to
HTTP servers
.IP \(bu 4
mod_rewrite(4gx) \(em http(8gx) processing plugin for altering HTTP request
URIs before processing
.IP \(bu 4
zcore(8gx)
.SH Mail retrieval agent subsystem
.IP \(bu 4
gromox\-mra.target(8gx) \(em MRA service group unit for systemd
.IP \(bu 4
imap(8gx) \(em IMAP server
.IP \(bu 4
midb_agent(4gx) \(em Service plugin for conversing with midb(8gx)
.IP \(bu 4
pop3(8gx) \(em POP3 server
.SH Local delivery agent
.IP \(bu 4
alias_translator(4gx) \(em Alias resolution plugin for delivery(8gx)
.IP \(bu 4
delivery(8gx) \(em Backend for local delivery
.IP \(bu 4
domain_list(4gx) \(em instance of str_table(4gx)
.IP \(bu 4
gromox\-mta.target(8gx) \(em MTA service group unit for systemd
.IP \(bu 4
message_enqueue(4gx) \(em Message enqueueing flusher plugin for smtp(8gx)
.IP \(bu 4
smtp(8gx) \(em SMTP frontend for local delivery
.IP \(bu 4
str_filter(4gx)
.IP \(bu 4
str_table(4gx) \(em string table match plugin
.SH System administration
.IP \(bu 4
pam_gromox(8gx) \(em a PAM plugin to authenticate with Gromox
.IP \(bu 4
rtf2html(1gx) \(em C++ helper for php_mapi's mapi_decompressrtf function

.IP \(bu 4
adaptor(8gx)
.IP \(bu 4
digest(8gx)
.IP \(bu 4
event(8gx)
.IP \(bu 4
freebusy(8gx) \(em C++ helper for the EWS Freebusy mechanism
.IP \(bu 4
gromox\-dbop(8gx) \(em Database maintenance utility
.IP \(bu 4
gromox\-mailq(8gx) \(em SMTP queue lister
.IP \(bu 4
gromox\-sa.target(8gx) \(em system administration service group unit for
systemd
.IP \(bu 4
mkmidb(8gx)
.IP \(bu 4
mkprivate(8gx)
.IP \(bu 4
mkpublic(8gx)
.IP \(bu 4
rebuild(8gx)
.IP \(bu 4
sa.cfg(5gx) \(em configuration file for system administration CGI programs
.IP \(bu 4
timer(8gx) \(em deferred command executor
.SH Service plugins
.IP \(bu 4
at_client(4gx) \(em Service plugin for deferred command execution with at(1)
.IP \(bu 4
authmgr(4gx) \(em Demultiplexer for authentication requests
.IP \(bu 4
ip6_container(4gx) \(em trivial source connection counter
.IP \(bu 4
ldap_adaptor(4gx) \(em LDAP connector for user metadata and authentication
.IP \(bu 4
log_plugin(4gx) \(em service plugin for a delayed fiel logger
.IP \(bu 4
logthru(4gx) \(em service plugin for a stdout logger
.IP \(bu 4
mysql_adaptor(4gx) \(em MySQL/MariaDB connector for user metadata and
authentication
.IP \(bu 4
textmaps(4gx) \(em Various data maps
.IP \(bu 4
timer_agent(4gx) \(em Service plugin for deferred command execution with
timer(8gx)
.SH Language bindings
.IP \(bu 4
mapi(4gx) \(em PHP module for Gromox services
.SH Listening sockets
.IP \(bu 4
/run/gromox/zcore.sock \(em zcore(8gx)
.IP \(bu 4
*:25 \(em smtp(8gx) SMTP service
.IP \(bu 4
*:80 \(em http(8gx) HTTP service
.IP \(bu 4
*:110 \(em pop3(8gx) POP3 service
.IP \(bu 4
*:143 \(em imap(8gx) IMAP service
.IP \(bu 4
*:443 \(em http(8gx) HTTP over implicit TLS
.IP \(bu 4
*:993 \(em imap(8gx) IMAP over implicit TLS
.IP \(bu 4
*:995 \(em pop3(8gx) POP3 over implicit TLS
.IP \(bu 4
*:1080 \(em external httpd(8) to run system_admin(7gx) CGI programs
.IP \(bu 4
*:2080 \(em external httpd(8) to run domain_admin(7gx) CGI programs
.IP \(bu 4
[::1]:3344 \(em zcore(8gx) management console
.IP \(bu 4
[::1]:4455 \(em imap(8gx) management console
.IP \(bu 4
[::1]:5000 \(em exmdb_provider(4gx) plugin inside http(8gx)
.IP \(bu 4
[::1]:5555 \(em midb(8gx) service
.IP \(bu 4
[::1]:5566 \(em smtp(8gx) management console
.IP \(bu 4
[::1]:6666 \(em timer(8gx) service
.IP \(bu 4
[::1]:7788 \(em pop3(8gx) management console
.IP \(bu 4
[::1]:8899 \(em http(8gx) management console
.IP \(bu 4
[::1]:9900 \(em midb(8gx) management console
.IP \(bu 4
[::1]:22222 \(em pad(8gx) service
.IP \(bu 4
[::1]:33333 \(em event(8gx) service
.SH Files
.IP \(bu 4
/usr/lib/gromox/libgxf_*.so: flusher plugins for smtp(8gx)
.IP \(bu 4
/usr/lib/gromox/libgxh_*.so: HTTP processing plugins for http(8gx)
.IP \(bu 4
/usr/lib/gromox/libgxm_*.so: hook plugins for delivery(8gx)
.IP \(bu 4
/usr/lib/gromox/libgxp_*.so: PDU processing plugins for http(8gx)
.IP \(bu 4
/usr/lib/gromox/libgxs_*.so: service plugins
