.TH gromox 7 "" "Gromox" "Gromox user reference"
.SH Synopsis
.PP
gromox \(em overview of the Gromox groupware server
.SH Agent subsystem
.IP \(bu 4
freebusy(8gx)
.IP \(bu 4
digest(8gx)
.IP \(bu 4
gromox\-agent.target(8gx) \(em agent service group unit for systemd
.IP \(bu 4
mapi(4gx) \(em PHP module for Gromox services
.IP \(bu 4
rtf2html(1gx) \(em RTFCP to HTML converter
.SH Archiving subsystem
.IP \(bu 4
archive(8gx)
.IP \(bu 4
cidb(8gx)
.IP \(bu 4
gromox\-archive.target(8gx) \(em systemd target replacing titan
.IP \(bu 4
migrator(8gx)
.SH Domain administration subsystem
.IP \(bu 4
da.cfg(5gx) \(em configuration file for domain administration CGI programs
.IP \(bu 4
da_daemon(8gx)
.IP \(bu 4
fcgi_cgi(8gx)
.IP \(bu 4
gromox\-da.target(8gx) \(em domain administration service group unit for
systemd
.IP \(bu 4
synchronizer(8gx)
.SH Exchange subsystem
.IP \(bu 4
exchange_emsmdb(4gx) \(em http(8gx) processing plugin for the Wire Format
Protocol (Outlook/Exchange RPCs).
.IP \(bu 4
exchange_nsp(4gx) \(em http(8gx) processing plugin for the Exchange Server Name
Service Provider Interface Protocol.
.IP \(bu 4
exchange_rfr(4gx) \(em http(8gx) processing plugin for the Address Book Name
Service Provider Interface Referral Protocol.
.IP \(bu 4
exmdb_provider(4gx) \(em http(8gx) service plugin for exmdb connections
.IP \(bu 4
http(8gx)
.IP \(bu 4
midb(8gx)
.IP \(bu 4
zcore(8gx)
.SH Mail retrieval agent subsystem
.IP \(bu 4
gromox\-mra.target(8gx) \(em MRA service group unit for systemd
.IP \(bu 4
imap(8gx) \(em IMAP server
.IP \(bu 4
pop3(8gx) \(em POP3 server
.SH Mail transport agent subsystem
.IP \(bu 4
delivery(8gx)
.IP \(bu 4
gromox\-mta.target(8gx) \(em MTA service group unit for systemd
.IP \(bu 4
smtp(8gx) \(em SMTP server
.SH System administration subsystem
.IP \(bu 4
adaptor(8gx)
.IP \(bu 4
bl_delete(8gx)
.IP \(bu 4
cdnd(8gx)
.IP \(bu 4
event(8gx)
.IP \(bu 4
gromox\-sa.target(8gx) \(em system administration service group unit for
systemd
.IP \(bu 4
locker(8gx)
.IP \(bu 4
mkmidb(8gx)
.IP \(bu 4
mkprivate(8gx)
.IP \(bu 4
mkpublic(8gx)
.IP \(bu 4
monitor(8gx)
.IP \(bu 4
pad(8gx)
.IP \(bu 4
rebuild(8gx)
.IP \(bu 4
rsyncd(8gx)
.IP \(bu 4
rsyncer(8gx)
.IP \(bu 4
sa.cfg(5gx) \(em configuration file for system administration CGI programs
.IP \(bu 4
sa_daemon(8gx)
.IP \(bu 4
scanner(8gx)
.IP \(bu 4
sendmail(8gx)
.IP \(bu 4
sensor(8gx)
.IP \(bu 4
session(8gx)
.IP \(bu 4
supervisor(8gx)
.IP \(bu 4
timer(8gx)
.SH Service plugins
.IP \(bu 4
authmgr(4gx) \(em demultiplexer for authentication requests
.IP \(bu 4
ldap_adaptor(4gx) \(em LDAP connector for user metadata and authentication
.IP \(bu 4
mysql_adaptor(4gx) \(em MySQL/MariaDB connector for user metadata and
authentication
.SH Listening sockets
.IP \(bu 4
/run/gromox/fcgi_cgi.sock \(em fcgi_cgi(8gx)
.IP \(bu 4
/run/gromox/zcore.sock \(em zcore(8gx)
.IP \(bu 4
*:25 \(em smtp(8gx) SMTP service
.IP \(bu 4
*:80 \(em http(8gx) HTTP service
.IP \(bu 4
*:110 \(em pop3(8gx) POP3 service
.IP \(bu 4
*:143 \(em imap(8gx) IMAP service
.IP \(bu 4
*:443 \(em http(8gx) HTTP over implicit TLS
.IP \(bu 4
*:993 \(em imap(8gx) IMAP over implicit TLS
.IP \(bu 4
*:995 \(em pop3(8gx) POP3 over implicit TLS
.IP \(bu 4
*:1080 \(em external httpd(8) to run system_admin(7gx) CGI programs
.IP \(bu 4
*:2080 \(em external httpd(8) to run domain_admin(7gx) CGI programs
.IP \(bu 4
127.0.0.1:3344 \(em zcore(8gx) management console
.IP \(bu 4
127.0.0.1:4455 \(em imap(8gx) management console
.IP \(bu 4
127.0.0.1:5000 \(em exmdb_provider(4gx) plugin inside http(8gx)
.IP \(bu 4
127.0.0.1:5555 \(em midb(8gx) service
.IP \(bu 4
*:5556 \(em cidb(8gx) service
.IP \(bu 4
127.0.0.1:5566 \(em smtp(8gx) management console
.IP \(bu 4
127.0.0.1:6666 \(em timer(8gx) service
.IP \(bu 4
127.0.0.1:7777 \(em locker(8gx) service
.IP \(bu 4
127.0.0.1:7788 \(em pop3(8gx) management console
.IP \(bu 4
*:8000 \(em relay_agent(4gx) hook plugin inside delivery(8gx)
.IP \(bu 4
*:8888 \(em multiple_retrying(4gx) service plugin
.IP \(bu 4
127.0.0.1:8899 \(em http(8gx) management console
.IP \(bu 4
127.0.0.1:9900 \(em midb(8gx) management console
.IP \(bu 4
127.0.0.1:9999 \(em session(8gx) service
.IP \(bu 4
127.0.0.1:10000 \(em cdnd(8gx) service
.IP \(bu 4
127.0.0.1:11111 \(em sensor(8gx) service
.IP \(bu 4
127.0.0.1:22222 \(em pad(8gx) service
.IP \(bu 4
127.0.0.1:33333 \(em event(8gx) service
.IP \(bu 4
*:44444 \(em rsyncd(8gx) service
.SH Connections to external services
.IP \(bu 4
*:9312: from cidb(8gx) to a Sphinx search engine
.IP \(bu 4
*:10001: from cdner_agent(4gx) to ...
