.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2022 grommunio GmbH
.TH gromox\-dbop 8gx "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-mbop \(em Mailbox operations utility
.SH Synopsis
\fBgromox\-mbop\fP {\fB\-d\fP \fImbox\fP|\fB\-u\fP \fIu@d.de\fP} \fIcommand\fP
[command-args...]
.SH Global options
.TP
\fB\-d\fP \fI/var/lib/gromox/user/1/2\fP
Lookup the mailbox parameters from the associated filesystem location.
.TP
\fB\-u\fP \fIu@d.de\fP
Lookup the mailbox parameters from the associated username.
.SH Commands
.IP \(bu 4
delmsg: issue "delete_message" RPCs for a mailbox
.IP \(bu 4
unload: issue the "unload_store" RPC for a mailbox
.IP \(bu 4
vacuum: issue the "vacuum" RPC for a mailbox
.SH delmsg
.SS Synopsis
\fBgromox\-mbop \-u\fP \fIa@b.de\fP \fBdelmsg \-f\fP \fIfolder_spec\fP
[\fImsgid\fP...]
.SS Description
This command hard-deletes messages from a store, including issuing proper
PR_CHANGE_KEY metadata updates for the sake of Cached Mode clients.
.PP
The folder and message IDs taken as arguments on the command-line should be
of the GC-value form, i.e. as they appear in the the SQLite database.
.SS Subcommand options
.TP
\fB-f\fP \fIfolder_spec\fP
The folder from which to delete the messages. See below for details. (If a
msgid is specified which is not located in the particular folder, that message
will not be deleted.)
.TP
\fB\-\-soft\fP
Perform a soft deletion.
.SH emptyfld
.SS Synopsis
\fBgromox\-mbop \-u\fP \fIa@b.de\fP \fBemptyfld\fP [\fB\-R\fP] [\fB\-\-soft\fP]
\fIfolder_spec\fP...
.SS Description
This command deletes messages from a folder.
.SS Subcommand options
.TP
\fB-R\fP
Besides messages, also delete subfolders.
.TP
\fB\-\-soft\fP
Perform a soft deletion. (This feature is experimental.) Default is hard.
.SH unload
Normally, exmdb_provider(4gx) keeps stores open for up to
exmdb_provider.cfg:cache_interval. The "unload_store" RPC to
exmdb_provider(4gx) causes the sqlite database (in
/var/lib/gromox/.../exmdb/exchange.sqlite3) to be closed. Any subsequent RPC
may reopen it, though. The unload RPC is useful after a mailbox was deleted
and/or reinitialized with grommunio-admin-api or tools like
gromox-mkprivate(8)/gromox-mkpublic(8). [zcore also has store state in memory.
This would also need to be purged \(em but there is no RPC for such action at
this time.] unload will fail to succeed if there is still a client connected to
the mailbox via a notification channel.
.SH vacuum
The "vacuum" RPC makes exmdb_provider issue the SQLite "vacuum" command on
exchange.sqlite3, which rebuilds and compacts the database file.
.SH clear-photo
From Gromox 2.9.53 onwards, the user's profile picture is stored in the Gromox
"exchange.sqlite3" database, and "portrait.jpg" in the filesystem has been
obsoleted. The clear-photo command will delete the user picture from the SQLite
db. Note that, when there is no mailbox-level profile picture set, Gromox
server processes may serve an image from another source, e.g. LDAP.
.SH clear-profile
Similar to MSMAPI, PHP-MAPI keeps a MAPI profile which contains a store list
and also the settings for grommunio-web. From Gromox 2.9.55, the MAPI profile
is stored in the Gromox "exchange.sqlite3" database, and "zarafa.dat" in the
filesystem has been obsoleted. The clear-profile command will delete the
profile from the SQLite db.
.SH Folder specification
\fIfolder_spec\fP can either be a numeric identifier, or a path-like
specification into the folder hierarchy. If the name starts with the slash
character '/', it is interpreted as starting from the root; otherwise, the
first component must be a special name (CALENDAR, COMMON_VIEWS, CONFLICTS,
CONTACTS, DEFERRED_ACTION, DELETED, DRAFT, FINDER, INBOX, IPM_SUBTREE, JOURNAL,
JUNK, LOCAL_FAILURES, NOTES, OUTBOX, SENT, SERVER_FAILURES, SHORTCUTS,
SYNC_ISSUES, TASKS, VIEWS). These special names can be used with private stores
only; there are no names defined for public folder contents at this time. There
is also no parsing support for slashes in folder names currently in mbop; the
slash character is always treated as a hierarchy separator. Examples:
.IP \(bu 4
/Top of Information Store/Sent Items/2022
.IP \(bu 4
IPM_SUBTREE/Sent Items/2022
.IP \(bu 4
SENT/2022
.SH See also
\fBgromox\fP(7)
