.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2020-2022 grommunio GmbH
.TH gromox\-dbop 8gx "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-dbop \(em User database maintenance utility
.SH Synopsis
\fBgromox\-dbop [\-CU\fP] [\fB\-\-create\-old\fP] [\fB\-c\fP
\fImysql_adaptor.cfg\fP]
.SH Options
.TP
\fB\-C\fP
Create the initial set of tables for the user information database (in MySQL).
.TP
\fB\-U\fP
Upgrade the schema of the user information database. The database
(MYSQL_DBNAME) should exist and be blank.
.TP
\fB\-\-create\-old\fP
Create blank initial database using version 0. (This can be used for testing
the upgrade procedure.)
.TP
\fB\-c\fP \fImysql_adaptor.cfg\fP
Path to a configuration file that defines MYSQL_HOST, MYSQL_USERNAME, etc. If
omitted, gromox\-dbop will read /etc/gromox/http.cfg to locate
mysql_adaptor.cfg to locate the mysql parameter.
.SH See also
\fBgromox\fP(7), \fBmysql_adaptor\fP(4gx)
