.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2024 grommunio GmbH
.TH gromox\-e2ghelper 8 "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-e2ghelper \(em Helper program for exchange2grommunio.ps1
.SH Description
e2ghelper is an implementation detail in the exchange2grommunio.ps1 script and
not meant to be called directly.
