.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2024–2025 grommunio GmbH
.TH gromox\-export 8 "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-export \(em Utility to export Gromox messages to various formats
.SH Synopsis
\fBgromox\-exm2eml \-u\fP \fIuser@domain.example\fP
[\fIfolder_id\fP\fB:\fP]\fImessage_id\fP
.PP
\fBgromox\-exm2ical \-u\fP \fIuser@domain.example\fP
[\fIfolder_id\fP\fB:\fP]\fImessage_id\fP
.PP
\fBgromox\-exm2vcf \-u\fP \fIuser@domain.example\fP
[\fIfolder_id\fP\fB:\fP]\fImessage_id\fP
.PP
\fBgromox\-exm2mt \-u\fP \fIuser@domain.example\fP
[\fIfolder_id\fP\fB:\fP]\fImessage_id\fP... >file.mt
.PP
\fBgromox\-exm2tnef \-u\fP \fIuser@domain.example\fP
[\fIfolder_id\fP\fB:\fP]\fImessage_id\fP >file.tnef
.SH Description
gromox-export reads one message from an exmdb information store and exports it
as Gromox Mailbox Transfer (GXMT) datastream, Internet Mail (RFC 5322),
iCalendar (RFC 5545), vCard (RFC 6350), or TNEF, depending on which name it was
invoked under. ("exm" is short for exmdb and refers to the network protocol
used to talk to the message store.)
.PP
When \fIfolder_id\fP is specified, the exporter validates that the message is
in that particular folder and fail the operation if it is not. In addition, the
importer will also use a different RPC, but this detail should not make a
difference to end-users.
.PP
An alternate way to get an EML representation is using grommunio-web's "Export
as > EML file(s)" function from the context menu of a mail item.
.SH Options
.TP
\fB\-Y\fP \fIvalue\fP
If set to 1, allday events are emitted as so-called floating dates.
If set to 0 however, allday events are emitted as precise-time events.
.br
Default: 1
\fB\-p\fP
Show properties in detail (enhances \fB\-t\fP).
.TP
\fB\-t\fP
As the source message is read, print a diagnostic tree view of the MAPI
properties to stderr.
.TP
\fB\-u\fP [\fIuser\fP]\fB@\fIdomin.example\fP
Source mail store from which to load the message from. For the public folder of
a domain, leave out the local part, i.e. use \fB@\fP\fIdomain.example\fP.
.TP
\fB\-\-loglevel\fP \fIn\fP Maximum verbosity of general logging (not connected
to \fB\-p\fP, \fB\-t\fP or \fB\-v\fP). 1=crit, 2=error, 3=warn, 4=notice,
5=info, 6=debug.
.br
Default: \fI4\fP (notice)
.SH See also
\fBgromox\fP(7), \fBgromox\-eml2mt\fP(8)
