.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2021-2022 grommunio GmbH
.TH gromox\-mkmidb 8gx "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-mkmidb \(em Tool for creating a blank message index database
.SH Synopsis
\fBgromox\-mkmidb\fP [\fB\-Uv\fP] [\fB\-c\fP \fIconfig\fP] [\fB\-fP\fP]
\fIusername\fP
.SH Options
.TP
\fB\-U\fP
Rather than creating the SQLite file, upgrade it. (The \-f option has no
effect.) mkmidb does not coordinate with mkmidb(8gx) and data corruption is
possible if both try to edit the file at the same time. You should let
mkmidb(8gx) do upgrades instead, via the "midb_schema_upgrades" directive, or
at the very least, stop midb when using mkmidb \-U.
.TP
\fB\-c\fP \fIconfig\fP
Read configuration directives from the given file. If this option is not
specified, /etc/gromox/mysql_adaptor.cfg will be read for MySQL connection
parameters if that file exists.
.TP
\fB\-f\fP
Force overwrite when an existing SQLite database is detected for the user.
By default, mkmidb will not touch midb.sqlite3.
.TP
\fB\-v\fP
Turn on verbose mode for \-U.
.TP
\fB\-\-create\-old\fP
Create blank initial database using version 0. (This can be used for testing
the upgrade procedure.)
.TP
\fB\-\-integrity\fP
Perform SQLite integrity check.
.TP
\fB\-?\fP
Display option summary.
.SH Files
.IP \(bu 4
\fI/var/lib/gromox/...\fP/exmdb/midb.sqlite3: Message index database for IMAP.
.SH See also
\fBgromox\fP(7), \fBgromox\-mkprivate\fP(8gx), \fBmidb\fP(8gx),
\fBmysql_adaptor\fP(4gx)
