.\" SPDX-License-Identifier: CC-BY-SA-4.0 or-later
.\" SPDX-FileCopyrightText: 2022 grommunio GmbH
.TH gromox\-dbop 8gx "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-mbop \(em Mailbox operations utility
.SH Synopsis
\fBgromox\-mbop\fP {\fB\-d\fP \fImbox\fP|\fB\-u\fP \fIu@d.de\fP} \fIcommand\fP
[command-args...]
.SH Global options
.TP
\fB\-d\fP \fI/var/lib/gromox/user/1/2\fP
Lookup the mailbox parameters from the associated filesystem location.
.TP
\fB\-u\fP \fIu@d.de\fP
Lookup the mailbox parameters from the associated username.
.SH Commands
.IP \(bu 4
delmsg: issue "delete_message" RPCs for a mailbox
.IP \(bu 4
unload: issue the "unload_store" RPC for a mailbox
.IP \(bu 4
vacuum: issue the "vacuum" RPC for a mailbox
.SH delmsg
.SS Synopsis
\fBgromox\-mbop \-u\fP \fIa@b.de\fP \fBdelmsg \-f\fP \fIfolder_id\fP
[\fImsgid\fP...]
.SS Description
This command hard-deletes messages from a store, including issuing proper
PR_CHANGE_KEY metadata updates for the sake of Cached Mode clients.
.PP
The folder and message IDs taken as arguments on the command-line should be
of the GC-value form, i.e. as they appear in the the SQLite database.
.SS Subcommand options
.TP
\fB-f\fP \fIfolder_id\fP
The folder from which to delete the messages. (If a msgid is specified which is
not located in the particular folder, that message will not be deleted.)
.TP
\fB\-\-soft\fP
Perform a soft deletion.
.SH emptyfld
.SS Synopsis
\fBgromox\-mbop \-u\fP \fIa@b.de\fP \fBemptyfld\fP [\fB\-R\fP] [\fB\-\-soft\fP]
\fIfolder_id\fP...
.SS Description
This command deletes messages from a folder.
.SS Subcommand options
.TP
\fB-R\fP
Besides messages, also delete subfolders.
.TP
\fB\-\-soft\fP
Perform a soft deletion. (This feature is experimental.) Default is hard.
.SH unload
Normally, exmdb_provider(4gx) keeps stores open for up to
exmdb_provider.cfg:cache_interval. The "unload_store" RPC to
exmdb_provider(4gx) causes the sqlite database (in
/var/lib/gromox/.../exmdb/exchange.sqlite3) to be closed. Any subsequent RPC
may reopen it, though. The unload RPC is useful after a mailbox was deleted
and/or reinitialized with grommunio-admin-api or tools like
gromox-mkprivate(8)/gromox-mkpublic(8). [zcore also has store state in memory.
This would also need to be purged \(em but there is no RPC for such action at
this time.] unload will fail to succeed if there is still a client connected to
the mailbox via a notification channel.
.SH vacuum
The "vacuum" RPC makes exmdb_provider issue the SQLite "vacuum" command on
exchange.sqlite3, which rebuilds and compacts the database file.
.SH See also
\fBgromox\fP(7)
