.TH gromox\-oxm2mt 8 "" "Gromox" "Gromox admin reference"
.SH Name
gromox\-oxm2mt \(em Utility for analysis of Outlook .msg files
.SH Synopsis
\fBgromox\-oxm2mt\fP [\fB\-pt\fP] \fIinput.msg\fP
.SH Description
gromox\-oxm2mt reads an Outlook .msg file, and re-exports the data in a
Gromox-specific mailbox transfer format to stdout for consumption by pipe by
the gromox-mt2exm(8gx) program. Optionally, oxm2mt can print a tree summary of
the message.
.SH Options
.TP
\fB\-p\fP
Show properties in detail (enhances \fB\-t\fP).
.TP
\fB\-t\fP
Show a diagnostic tree view of the source data as it is being read.
.SH Examples
Import of a message to drafts:
.PP
gromox\-oxm2mt saved.msg | gromox\-mt2exm \-u target@mailbox.de \-B drafts
.SH Normative references
.IP \(bu 4
MS-CFB: Compound File Binary Format (CFBF)
.IP \(bu 4
MS-OXMSG: Outlook Item (.msg) File Format
.PP
Outlook message files use the "Object Linking and Embedding (OLE) / Component
Object Model (COM) structured storage compound file implementation binary file
format", or just CFB/CFBF for short. It resembles something of a FAT
filesystem. The file(1) utility identifies those as "CDFV2 Microsoft Outlook
Message" (Compound Document Format). A proposed MIME type is
"application/vnd.ms-outlook".
.PP
oxm2mt uses the libolecf C library to read the CDF structure of .msg files
per [MS-CFB], and then applies own code to make sense of the files as per
[MS-OXMSG].
.SH See also
\fBgromox\fP(7), \fBgromox\-mt2exm\fP(8gx), \fBolecfexport(1)\fP
