#!/bin/sh


mkdir /var/athena
cp -R * /var/athena
ln -s /var/herculiz /var/athena/gateway
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /var/herculiz -s /bin/nologin
touch /var/athena/logs/athena_log.txt
chown -R herculiz:herculiz /var/athena
chmod -R a+wr /var/athena
mv /var/athena/bin/athena.bin /usr/bin/athena
mv /var/athena/bin/athena.sh /etc/rc.d/init.d/athena
rm -f /var/athena/bin/athena.service
chkconfig --add athena
chown -R herculiz:herculiz /var/athena
echo "ATHENA mail system administration is installed OK"
echo
