#!/bin/sh


mkdir /var/titan
cp -R * /var/titan
groupadd -g 801 titan
useradd titan -u 801 -g titan -d /var/titan -s /bin/nologin
chown -R titan /var/titan
chmod -R a+wr /var/titan
mv /var/titan/bin/titan.bin /usr/bin/titan
mv /var/titan/bin/titan.sh /etc/rc.d/init.d/titan
rm -f /var/titan/bin/titan.service
chkconfig --add titan
echo "TITAN archive services is installed OK"
echo
