#!/bin/sh

RELEASE_HOME='release'
BIN_DIR='bin'
TOOLS_DIR='tools'
CONFIGS_DIR='config'
DATA_DIR='data'
LIB_DIR='lib'
TOKEN_DIR='token'
LOGS_INFO='logs'
COMMON_LIB='common.so'
EMAIL_LIB='email_lib.so'

rm -rf $RELEASE_HOME
mkdir $RELEASE_HOME
mkdir $RELEASE_HOME/$BIN_DIR
mkdir $RELEASE_HOME/$TOOLS_DIR
mkdir $RELEASE_HOME/$CONFIGS_DIR
mkdir $RELEASE_HOME/$DATA_DIR
mkdir $RELEASE_HOME/$LIB_DIR
mkdir $RELEASE_HOME/$TOKEN_DIR
mkdir $RELEASE_HOME/$LOGS_INFO
cp scripts/install* $RELEASE_HOME
cp scripts/format_area.sh $RELEASE_HOME/$TOOLS_DIR
cp titan/titan.bin $RELEASE_HOME/$BIN_DIR
cp scripts/titan.sh $RELEASE_HOME/$BIN_DIR
cp scripts/titan.service $RELEASE_HOME/$BIN_DIR
cp config/titan.cfg $RELEASE_HOME/$CONFIGS_DIR
cp data/*.txt $RELEASE_HOME/$DATA_DIR
cp doc/mysql.txt $RELEASE_HOME/$TOOLS_DIR
cp common/$COMMON_LIB $RELEASE_HOME/$LIB_DIR
cp email_lib/$EMAIL_LIB $RELEASE_HOME/$LIB_DIR
cp cidb/cidb $RELEASE_HOME/$BIN_DIR
cp archive/archive $RELEASE_HOME/$TOOLS_DIR
cp migrator/migrator $RELEASE_HOME/$TOOLS_DIR
dos2unix $RELEASE_HOME/$BIN_DIR/titan.sh
chmod a+rx $RELEASE_HOME/$BIN_DIR/*.sh
