#!/bin/sh

MAKE=make
PARAM_SIZE=$#

if [ $PARAM_SIZE -eq 1 ];then
	DIR_LIST=`ls -l|grep '^d'|grep -v 'CVS\$'|grep -v 'doc$'|grep -v 'lib$'|grep -v 'config'|grep -v 'include$'|grep -v 'data$'|awk '{print \$NF}'`
elif [ $PARAM_SIZE -gt 1 ];then
	DIR_LIST=`cat $2`
fi

for EACH_DIR in $DIR_LIST
do
	cd $EACH_DIR
	RESULT=$?
	if [ $RESULT -ne 0 ];then
		exit 1
	fi
	$MAKE $1
	RESULT=$?
	if [ $RESULT -ne 0 ];then
		exit 1
	fi
	cd ..
done
