#!/bin/sh


mkdir /var/pandora
cp -R * /var/pandora
chown -R apache /var/pandora
chmod -R a+wr /var/pandora
mv /var/pandora/bin/pandora.bin /usr/bin/pandora
mv /var/pandora/bin/pandora.sh /etc/rc.d/init.d/pandora
rm -f /var/pandora/bin/pandora.service
chkconfig --add pandora
echo "PANDORA webmail agent services is installed OK"
echo
