#!/bin/sh
if test "$1" != "-d"; then
	echo 'ERROR: The "cleaner" executable has been replaced by a gromox-mbop call.' >&2
	echo 'ERROR: cleaner (as a wrapper) no loner recognizes -n or -v.' >&2
	exit 1
fi
echo 'NOTE: This program has been replaced by `gromox-mbop -d '"$2"' purge-datafiles`.' >&2
echo 'Forwarding execution...' >&2
exec gromox-mbop -d "$2" purge-datafiles
