#!/usr/bin/perl
print sort {
	my($x, $y) = ($a, $b);
	chomp($x);
	chomp($y);
	my $have_x = $x =~ s{.*\b(0x[0-9a-f]+).*}{$1}ig;
	my $have_y = $y =~ s{.*\b(0x[0-9a-f]+).*}{$1}ig;
	return 1 if (!$have_x && $have_y);
	return -1 if ($have_x && !$have_y);
	return $x cmp $y;
} <>;
