SCRIPTS_PATH=../scripts
#object files under "lib" directory, used for linking

.PHONY : normal
.PHONY : debug
.PHONY : link
.PHONY : clean
normal :
	@$(SCRIPTS_PATH)/compile normal
debug :
	@$(SCRIPTS_PATH)/compile debug
clean :
	@$(SCRIPTS_PATH)/compile clean
